language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.2.8
  - 2.3.7
bundler_args: --without acceptance
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
notifications:
  email:
    - biemond@gmail.com
    - junior.jairo1@gmail.com
env:
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.10.11
  - PUPPET_VERSION=5.5.1
matrix:
  exclude:
  - rvm: 2.2.8
    env: PUPPET_VERSION=5.5.1
  include:
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-7 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1404 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:11.0.0 BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:11.0.0 BEAKER_debug=true BEAKER_set=docker/debian-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.4.4
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:11.0.0 BEAKER_debug=true BEAKER_set=docker/ubuntu-1404
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
